### ISSUE TITLE
new test glob breaks node platform default app config

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#1112]
default `APP_CONF_DIR` is `test/configs`, while now we put everything inside `__tests__` folder

**Comment by ranyitz** [comment]
In fullstack apps that use `jest-yoshi-preset`, we use a custom `APP_CONF_DIR`, so the default does not matter much.

https://github.com/wix/yoshi/blob/f7c6c951ed953790ae5c3850ca1f395951b64a49/packages/create-yoshi-app/templates/fullstack/jest-yoshi.config.js#L19

What is the usecase?

**Comment by yanivefraim** [comment]
> In fullstack apps that use `jest-yoshi-preset`, we use a custom `APP_CONF_DIR`, so the default does not matter much.
> 
> [yoshi/packages/create-yoshi-app/templates/fullstack/jest-yoshi.config.js](https://github.com/wix/yoshi/blob/f7c6c951ed953790ae5c3850ca1f395951b64a49/packages/create-yoshi-app/templates/fullstack/jest-yoshi.config.js#L19)
> 
> Line 19 in [f7c6c95](/wix/yoshi/commit/f7c6c951ed953790ae5c3850ca1f395951b64a49)
> 
>  appConfDir, 
> What is the usecase?

My use case is existing projects, which do not use `index-dev` file for their `yoshi start` command. They can add their own `APP_CONF_DIR` when migrating to `yoshi V4` (`APP_CONF_DIR=__tests__/configs yoshi start`, for example), but this is something that we did not think about when moving to __tests__

**Comment by ranyitz** [comment]
Can you explain what breaks?

Is there an error? Is it looks weird that `test/config` is generated instead of `__tests__/config`?

_____________________

There is this bug - https://github.com/wix/yoshi/issues/922.
I thought about a solution where we can configure those environment parameters on the test process, so users won't need to explicitly provide them on `jest-yoshi.config`

We can use the same logic in order to preconfigure the node_platform's environment params on start. (instead of in every project)

**Comment by ronami** [comment]
I think we solved it in #1118. Can this be closed?
