### ISSUE TITLE
Make `strictExportPresence` configurable

### ISSUE THREAD

**Issue by muteor** [wix/yoshi#1169]
# 🙋 Feature Request

Allow `strictExportPresence` to be configured inside yoshi config.

We use typescript and like to organise our code by exporting interfaces from index files so they are easy to import. This style causes false export warnings in webpack as detailed in #179 .

### 😯 Current Behavior

Webpack dies on warnings like:

```
ERROR in ./client/components/FacetStream/index.ts 2:0-69
"export 'FacetStreamChildrenProps' was not found in './types'
```

### 🤔 Expected Behavior

Webpack should ignore the warnings.

### 🔦 Context

```
@wix/da-browse@1.0.0 /Users/keith/Sites/da-frontend/projects/da-browse
└─┬ yoshi@4.1.0-rc.4
  └── ts-loader@5.3.3
```

**Comment by ronami** [comment]
Normally, In Webpack v4 missing exports result in a warning. Setting `strictExportPresence` to `true` will turn them into errors.

I think that an error is most likely better here, as we want to fail on missing exports. You're describing a specific use-case (#179) where re-exporting TypeScript types will cause Webpack to show a warning/error, while in fact, it shouldn't.

We solved it in Yoshi v3 by completely suppressing these errors (#459), and, while it did solve the problem, it meant not catching errors (that we otherwise can), during build time. I looked a bit and found this suggestion: https://github.com/babel/babel-loader/issues/603#issuecomment-418472968. It's a workaround, but it has a small footprint on the project, and it means that we will still be able to show missing exports errors where it's valid.

I tried re-exporting (`*`) in your project in this specific file and got a green build (there was only 1 use-case in your project).

What do you think? Does this make sense? I think our options here are either to keep this as an error (preferably IMO) or change this into a warning and suppress it (old flow).

cc @ranyitz @netanelgilad @yairhaimo

**Comment by muteor** [comment]
@ronami I can have a go at using `export *` and see how bigger migration it would be for us. I think it should work in most cases, the only problem I can foresee is when we rename a default export in the index. But we could then try the `export type` workaround.

Anyway will test it and get back to you.

**Comment by ronami** [comment]
Closing. Please re-open if it's still relevant.
