### ISSUE TITLE
yoshi: extract stylable from the js bundle

### ISSUE THREAD

**Issue by shlomitc** [wix/yoshi#1179]
# 🙋 Feature Request

### 😯 Current Behavior
Currently, any `stylable` file, is being bundled to the project's js file.
The reason this strategy was picked, is because stylable creates their own css bundle, for example, `app.stylable.css` and not concatenating to a single `app.css` like any other css pre-processor. 

It obviously works but has some downsides:
1. SSR doesn't work well, because styles can be loaded only after js bundle is parsed. so this also affects performance.
2. Many css style tags are added to the head, without a clear way to understand who added them, causing a mess.
3. Following the previous point, in platforms such as Wix's Business Manager, where multiple modules are loaded, this side effect adding style tags makes it impossible to clean when switching modules (moving between apps).
![image](https://user-images.githubusercontent.com/6093192/55005121-1e3d9180-4fe4-11e9-8041-f2e81a618702.png)

### 🤔 Expected Behavior

properly handle the stylable css files in a way which is not forcing the files to be loaded in js.

### 💁 Possible Solution 
1. find a way to concat the bundled css created from SASS and stylable.
2. allow an opt-in flag to separate the stylable css.

**Comment by shlomitc** [comment]
Still relevant

**Comment by ranyitz** [comment]
The main problem from the "developer experience" side is that we don't want to enforce developers to change things in their `html` (`vm`/`ejs`) depending on the files that they import (for example, if they are importing WSR component suddenly they'll need to import it into their template).

The problem here is that those stylable chunks are **initial chunks** meaning that they have to be downloaded during page load (in oppose to dynamically imported).

Another solution that we can go with, is the [experimentalBuildHtml](https://github.com/wix/yoshi/pull/1090) feature. So the user won't need to do anything by their side, and we could insert the stylable chunks if needed as initial chunks.

Of course, this is an idea for the future. We plan on everyone to use this feature so we could roll out features like the one suggested above.

**Comment by shlomitc** [comment]
Your idea sounds great, but what should happen in cases where html is not loaded? For example a business manager module declares a menifest and not an html. Same for OOO TPAs

**Comment by shlomitc** [comment]
still relevant

**Comment by shlomitc** [comment]
this is going to be solved by @ranyitz in a few weeks time when the output of the component libraries will be css and consumers will not need to bundle stylable
