### ISSUE TITLE
Option to allow sourcemaps with local build on app flow

### ISSUE THREAD

**Issue by ronenst** [wix/yoshi#1257]
# 🙋 Feature Request

### 😯 Current Behavior

Running `yoshi build` in dev generates statics with no sourcemaps (inline or otherwise) while the CI build has `.map` files generated for each static.

### 🤔 Expected Behavior

Have a flag (e.g., `yoshi build --with-local-sourcemaps`) that enables source maps. This is useful when using statics via `npm link` but not through the dev server.

### 💁 Possible Solution 

There is already an option in `createClientWebpackConfig()` but it seems there's no way to set it:
https://github.com/wix/yoshi/blob/master/packages/yoshi/config/webpack.config.js#L537

### 🔦 Context 

This is useful when serving `dist/statics` through a static express server which hosting applications (e.g. business-manager) use in their testkit.

Note: since investigating this, I've solved this via an `npm start` flow which might be more correct anyway.

**Comment by ranyitz** [comment]
@ronenst Just to be specific, There is a [`--source-map` option](https://wix.github.io/yoshi/docs/api/cli#source-map) option, that is working well during build.

You are using `app-flow`, and this feature is not supported there yet.

In order to support, we can take the cli argument `source-map` and pass it into `createClientWebpackConfig` function.

https://github.com/wix/yoshi/blob/6ac24ae87243a27a18e4c94c6b330cf6c7768c4d/packages/yoshi/src/commands/build-app.js#L109-L113

PRs welcome
