### ISSUE TITLE
Improve Yoshi integration with TeamCity

### ISSUE THREAD

**Issue by piratus** [wix/yoshi#1287]
# 🙋 Feature Request

Improve Yoshi integration with TeamCity

### 😯 Current Behavior

Currently Yoshi logs messages to stdout using natural language.

### 🤔 Expected Behavior

Yoshi uses [TeamCity Service Messages](https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity) for logging.

### 💁 Possible Solution 

- [ ] Make yoshi log messages in TeamCity format
- [ ] Add logger for webpack to:
  - [ ] log errors, warnings and performance hints as inspections
  - [ ] log build build progress/status
  - [ ] log asset sizes
- [ ] Add or enable reporters for:
  - [x] Jest (tests & coverage)
  - [ ] TSLint
  - [ ] ESLint
  - [ ] StyleLint

**Comment by ranyitz** [comment]
@piratus Thanks for opening this issue and sorry it took time to answer!

For now, when we use TeamCity I agree that it makes sense to give better support for linting in the CI. Regarding the Yoshi specific things, I don't know how hard would it be to maintain a custom TeamCity reporter.

@ronami @netanelgilad What do you think?

**Comment by netanelgilad** [comment]
I think adding linting (ts, es, style) reporters for Teamcity is great, and should be (🤞) easy, let's do it!

About creating custom reporters for yoshi to support Teamcity format, I'm not so sure. We are planning to move away from Teamcity, so maybe it would be best not to lock ourselves deeper into Teamcity. But more importantly I'd love to know what exactly you'd want to be integrated into teamcity (because those requirements are not really TC specific, and should be implemented in any CI solution we choose). Logging webpack errors/warnings in Teamcity format might be interesting to look at, so instead of having `build failed with status code 1` you'd get a more informative message, but I'm not sure I understand the other points, how would they be expressed in TC's UI? @piratus can you elaborate? maybe with screenshots of where it should appear?
