### ISSUE TITLE
Error when creating a library with create-yoshi-app

### ISSUE THREAD

**Issue by yaelz** [wix/yoshi#1321]
# :bug: Bug Report

### :hushed: Current Behavior

When creating a library with the Yoshi generator, the `yoshi lint --fix` step results in an error:

```
added 2267 packages from 1244 contributors in 87.46s

Running yoshi lint --fix

Command failed.

Packages related to Yoshi should be installed with the same major version as Yoshi:

  - jest-yoshi-preset (3.31.0)
  - yoshi-style-dependencies (3.16.0)
Please install them in the version 4.6.2.

/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/bin/create-yoshi-app.js:4
  throw error;
  ^

Error: Command failed: /bin/sh -c npx yoshi lint --fix
    at makeError (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/node_modules/execa/index.js:174:9)
    at module.exports.sync (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/node_modules/execa/index.js:338:15)
    at handleShell (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/node_modules/execa/index.js:117:9)
    at Function.module.exports.shellSync (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/node_modules/execa/index.js:361:43)
    at module.exports.lintFix.dir (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/src/utils.js:36:9)
    at module.exports (/Users/yaelz/.npm/_npx/3570/lib/node_modules/create-yoshi-app/src/createApp.js:48:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### :thinking_face: Expected Behavior

Create a library without errors

### :flashlight: Context
Tried to create a new library using Yoshi generator

### :footprints: Steps to Reproduce
```
npx create-yoshi-app experts-news-and-resources
and then: Choose project type › library
```
### :computer: Code Sample

Tried to create it under this repo:
https://github.com/wix-private/experts/

### :earth_africa: Your Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 12.0.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  3.17.0
    eslint-config-yoshi:  3.30.5
    eslint-config-yoshi-base:  3.30.5
    jest-environment-yoshi-bootstrap:  3.31.0
    jest-environment-yoshi-puppeteer:  3.31.0
    jest-yoshi-preset:  3.31.0
    storybook: Not Found
    tslint-config-yoshi:  3.30.5
    tslint-config-yoshi-base:  3.30.5
    typescript:  3.4.5
    webpack:  4.28.4
    yoshi-config:  4.5.0
    yoshi-helpers:  4.5.0
    yoshi-runtime:  1.0.110

 Zero config 🛴
```

**Comment by ranyitz** [comment]
@yaelz About the steps to reproduce.

After running the command, what did you choose?

**Comment by yaelz** [comment]
Right :) Updated above.

**Comment by ranyitz** [comment]
@yaelz Actually I wanted to know if it was TypeScript or JavaScript 😅 

But I've already generated both and everything worked.

I do have a thesis though for what happened.

Can you go to `~/` and run the same command from there? let me know if it works or not.

**Comment by ranyitz** [comment]
I think that the problem lies in this line:

https://github.com/wix/yoshi/blob/69e8940575e586feb4c5793fda82bd3ee6481925/packages/yoshi/src/verify-dependencies.js#L17

This project that you've created does not have those dependencies, and that's the reason the `verifyDependencies` function continued to go up and up until it has found another dependency in a different version and gave this false positive.

If that's true the solution is to search only in the node_modules of the directory itself, and not to perform a regular `require`.

@yaelz Thanks for opening this issue.

PRs welcome

**Comment by yaelz** [comment]
Just now seeing this! 
a. Created with no error under ~/ :-O Why is that?
b. I thought it came from that line as well. But the project I created does not have those dependencies, but it was created by Yoshi so it's weird that it's expecting some dependencies and didn't create it like it expected. It's in Yoshi's hands :) So I don't understand: What's the wanted behaviour?

**Comment by ranyitz** [comment]
I've explained it [in this comment](https://github.com/wix/yoshi/issues/1321#issuecomment-495204626), that's definitely an unintended behavior.

**Comment by agankarin** [comment]
So the issue is:
One of yoshi's dependencies was install with an old major version in the root folder, but the yoshi version in the subfolder was newer.
We want to avoid this case and this is why we have this check.

The solution to this issue can be one of the following: 
* upgrade the dependency in the root folder
* use the same yoshi version as the dependency
* run `create-yoshi-app` from root folder

To give a better visibility of this issue, we'll log also the full path of the dependency.
