### ISSUE TITLE
Autocomplete for Jest in VS code

### ISSUE THREAD

**Issue by litalwix** [wix/yoshi#1328]
# 🙋 Feature Request

### 😯 Current Behavior

Autocomplete for jest in VS code isn't implemented. I guess that the project should contain @types/jest, but it's not

### 🤔 Expected Behavior

Working autocomplete for Jest in VS code :)

### 💁 Possible Solution 

npm i --save-dev @types/jest is working. Tried also to install an addon for jest test support (VS code), but it didn’t work 

### 🔦 Context 

The main usage is for the expect function, to expose all of the verification functions easily instead of working manually with the API

**Comment by ranyitz** [comment]
@litalwix Thanks for opening this issue, you have a good argument.

`@types/jest` could benefit both TypeScript and JavaScript projects.

__TL;DR__
__The solution is to add `types/jest` to `jest-yoshi-preset`'s dependencies__

__Explanation why below...__
_______________

Let me share my thoughts about this:

* I think the best solution would be to add it you Yoshi's dependencies, so it will be installed for every project automatically.

* It will practically add completions for current users that don't have the types installed, and should not harm users that have `@types/jest` installed.

* What about developers that use TypeScript + mocha/jasmine and have `@types/mocha`/`@types/jasmine`?

* They will see the following error when running build/start:
![image](https://user-images.githubusercontent.com/11733036/58405606-86563580-8070-11e9-922f-5766b4cfd6fc.png)

* That happens because the two test runner types are clashing.

* We can though, know that every user of `jest-yoshi-preset` is indeed using `jest`, which means we can add the types to [`jest-yoshi-preset`'s dependencies](https://github.com/wix/yoshi/blob/master/packages/jest-yoshi-preset/package.json#L21) and be sure that all of its users use Jest.

_____________

@litalwix would you like to contribute a PR that fixes it?
