### ISSUE TITLE
change entry point of  the server

### ISSUE THREAD

**Issue by ofirdagan** [wix/yoshi#1450]
# 🙋 Feature Request

### 😯 Current Behavior
the `server.ts` has to be in the root folder. 

...

### 🤔 Expected Behavior
I want to change it to be in `my-fold/my-server-name.ts`

...

### 💁 Possible Solution 

...
remove hard coded checks ;)
### 🔦 Context 

...
10x! <3

**Comment by ranyitz** [comment]
If I understand you correctly, you want to change the entry point of the server to be configurable.

We make something configurable only if it brings real value. Having the server in one place as a convention is something we prefer, rather than to have a configuration that points to a different place in each project. We follow the [convension over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) paradigm. We want projects in Wix to be as similar as possible (code structure-wise), it will ease the movement between projects and teams, tools that rely on those conventions and more.

Please read https://github.com/prettier/prettier/issues/40#issue-199895633 to understand more about the general reasoning of resisting configuration.

Thanks for opening an issue and I hope that my explanation makes sense to you.
_________________________________________________

I want to give you a solution so you could have your logic wherever you'd like:

You can still have your server on `my-fold/my-server-name.ts` just have a `server.ts` on the root that `import`s it.

**Comment by ofirdagan** [comment]
it make sense obviously I strongly disagree :D
Having the client + server side code all mixed in one another doesn't make any sense to me. I would love to read an opinion about this project.

**Comment by ofirdagan** [comment]
as for the convention.. the convention imo should be looking in the `package.json` under the  yoshi entries just like npm.
it always good to follow other famous conventions

@shahata - WDYT?
