### ISSUE TITLE
Single executable

### ISSUE THREAD

**Issue by zemlanin** [wix/yoshi#1468]
# 🙋 Feature Request
Distribute `yoshi` (and related packages) as a single executable to make installs and updates faster

### 😯 Current Behavior
Because of more than two thousand dependencies (_excluding_ `devDependencies`), `yoshi` takes _a lot_ of time and storage to install. For example, having this `package.json`:

```json
{
  "name": "egg",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "yoshi": "^4.10.4"
  }
}
```

it will take a long time to install this package:
```
> npm i  // no package-lock.json, deleted node_modules
added 2096 packages from 1231 contributors in 233.738s

> npm i  // with package-lock.json, deleted node_modules
added 2096 packages from 1231 contributors in 27.096s

> yarn i  // no yarn.lock, deleted node_modules
✨  Done in 113.83s.

> yarn i  // with yarn.lock, deleted node_modules
✨  Done in 14.90s.
```

and package will be bigger than a quarter of a gigabyte
```
> du -h
...
4.0K	./node_modules/postcss-reduce-initial/dist
 12K	./node_modules/postcss-reduce-initial/data
 28K	./node_modules/postcss-reduce-initial
4.0K	./node_modules/setprototypeof/test
 24K	./node_modules/setprototypeof
288M	./node_modules
289M	.
```

### 🤔 Expected Behavior
<img width="322" alt="Smaller, Lighter, Faster" src="https://user-images.githubusercontent.com/711514/61642018-ddf7d280-aca8-11e9-9a67-eab62a4424d2.png">

### 💁 Possible Solutions
Moving most of `dependencies` to `devDependencies` and bundling `yoshi` before publishing it on npm

**Comment by ranyitz** [comment]
@zemlanin Thanks for this research!
you've raised some interesting points.
__________________________________________

1. We should all use yarn 😄 (According to your benchmark)
2. It's possible that distributing Yoshi into a single executable will improve install time, but we need to have a POC and see if it worth the trade-offs.
 * Would it be as easy to debug other build related dependencies as today?
 * How would it affect our build process?
 * How would it be installed on each project?

_____________________________

In my opinion, Yoshi is currently supporting too many use-cases in one package which means you are getting dependencies that you do not necessarily need. While this is solvable, it takes time and we need to make some big shifts in the current product.
We're aiming towards this direction with the `projectType` annotation in `package.json`. After we'll have different flows it would be easier to understand which dependency belongs to which flow and may reduce install times.

**Comment by Schniz** [comment]
I'm totally into this. I think it also relates to https://github.com/wix/yoshi/issues/931 which can be proof of concept for bundling a CLI for Yoshi.

> Would it be as easy to debug other build related dependencies as today?

I'm not sure I follow what do you mean here. When you bundle everything, there's no notion of "your webpack" anymore. No one has webpack on their project, they only have `yoshi`, and webpack is an implementation detail. I think it serves the idea of Yoshi itself. That being said, it is going to be harder to patch Yoshi if you want to experiment. I believe this is solvable with some hooks (like dynamic imports), so everything that is configurable, or act as configuration (webpack config, babel config, etc) can be next to the bundled `yoshi` binary, that can require them dynamically:

```
yoshi/
├── dist/
│   └── yoshi.bundle.js
├── bin/
│   └── yoshi.js
└── configs/
    ├── webpack.config.js
    ├── eslintrc.js
    └── babel.config.js
```

> How would it be installed on each project?

The same way we install today. Users will keep use `yoshi` as their root way of interacting with their build pipeline. The only thing we should think about is whether you want to have `jest` as a separate tool, so you can just call `jest` instead of `yoshi test` 😄 

I actually think we can make `yoshi test` check if `yoshi start` is already running, and skip build/cdn processes so `yoshi` would be the only way users interact with their apps.

> After we'll have different flows it would be easier to understand which dependency belongs to which flow and may reduce install times

We may or may not understand that, but bundling and tree-shaking stuff would be a much easier way to do it. Combining the `projectType`, Yoshi installation can get very fast!

**Comment by ronami** [comment]
That's interesting.

I think that in the current state of Yoshi it would be more harm than good, but after we remove some large dependencies (Protractor, Karma, Jasmine, etc) in v5, and thanks to @ranyitz awesome idea, possibly split each flow into its own package, this might be very helpful.

One problem I see with this approach is that we essentially shrinkwrap all of Yoshi's dependencies so some packages will be installed multiple times for users.
