### ISSUE TITLE
Add --no-server option to yoshi start

### ISSUE THREAD

**Issue by yakirn** [wix/yoshi#1576]
# 🙋 Feature Request

### 😯 Current Behavior

npx yoshi start --no-server
error: unknown option `--no-server'

### 🤔 Expected Behavior

Should spawn the CDN and do not spawn the app server.
This feature was active once, still in [the docs](https://wix.github.io/yoshi/docs/api/cli#no-server)

### 💁 Possible Solution 

If we decide we don't want it we should remove it from the docs, but I think it worth to add it :)

Thanks!

**Comment by amitdahan** [comment]
I think it's worth mentioning - this issue is only relevant for app-flow projects.
This project type is obviously super important and there seems to be a documentation issue that's not conveying this lack of configuration when opting for app-flow.
We're considering a few options to properly solve issues like this.
