### ISSUE TITLE
Support importing MP4 assets

### ISSUE THREAD

**Issue by ChasyaMargalit** [wix/yoshi#1580]
# 🙋 Feature Request

### 😯 Current Behavior

I cant import mp4 files
...

### 🤔 Expected Behavior

...

### 💁 Possible Solution 

Add mp4 in jest-yoshi-preset...

### 🔦 Context 

...

**Comment by amitdahan** [comment]
We spoke internally about the `.mp4` change you needed, it was decided that it won’t be added to yoshi/jest-preset, with the argument that many people will want to add more exotic and weird extensions (not that `.mp4` is that exotic/weird), and we want a better way rather than managing this "whitelist".

What we *can* offer is:
- After the #1564 this will _technically_ work, but only as far as `webpack` is concerned, tests will still fail.
- If you're using jest - this still will not work, since our jest-preset has the same "issue", except we couldn't use a "catch-all" transform, we have to use a whitelist there. We're working on a configuration override for our preset, that will allow you to somehow add more extensions and their custom transformer. Once that's done this'll be doable on the consuming project instead on all yoshi-based projects.
