### ISSUE TITLE
Make `esModuleInterop` default in all templates

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#1749]
## Summary

TypeScript projects which emit declarations, [emit different declaration files](https://github.com/microsoft/TypeScript/issues/28009) according to their `esModuleInterop` configuration.

Right now, since our `library` template does not use `esModuleInterop`, its declaration files are incompatible with the rest of our templates and potential-consumers. This was actually surfaced 2 days ago in @selama 's problem with consuming a `library` based project in some other template based project (that came with `esModuleInterop`).

As of today, `tsc --init` generates a `tsconfig.json` which certain up-to-date best-practices in mind, and it does specify `esModuleInterop: true`.

I believe the right choice is to enable `esModuleInterop` across all templates, but if we find enough reasons to disable it, I think it's important to have our templates be consistent with this decision.

**Comment by ranyitz** [comment]
@amitdahan Using good defaults is a good way indeed and it should be done.

The second tier would be to enable the [tsconfig enforcer](https://github.com/wix/yoshi/blob/1e06b0a6b6ff12f0234d78fde5c1e7455427395e/packages/yoshi-common/src/typescript/tsconfig-enforcer.ts#L24) on other flows, it's currently only works on the library flow.

It will suggest you to use the following in case you don't have it configured
```json
 esModuleInterop: true
```

We can maybe even enforce it (instead of suggest using it)

_____________________

It worth asking this question in with a broader audience to see if we're missing something.
