### ISSUE TITLE
Typescript project takes long time to build

### ISSUE THREAD

**Issue by yanivefraim** [wix/yoshi#1800]
I noticed that running `yoshi build` on a newly generated TS project takes ~30 sec. The 'blame' seems to be on [`fork-ts-checker`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin).
 
I think that the reason is that we have a lot of `@types` which are checked (adding `skipLibCheck=true` seems to solve the problem).

We should discuss about a proper solution.

**Comment by NitayRabi** [comment]
I had a look at [this issue](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/196) which might be related, and We can have a look at [CRA's approach to this](https://github.com/facebook/create-react-app/pull/5903).

In any case IMO libCheck is quite important for most projects (unless you're not maintaining it properly)

**Comment by amitdahan** [comment]
Hey sorry for barging in like this, just wanted to mention Next.js's approach - they insist on suggesting `skipLibCheck` in your `tsconfig.json`. If you don't override it to `false`, they add it to your `tsconfig.json` for you.
I couldn't find references to any communication happening about this decision, just [this PR](https://github.com/zeit/next.js/pull/7125).

**Comment by NitayRabi** [comment]
@giladsegal - would like to hear your opinion on the matter :)

**Comment by giladsegal** [comment]
using `skibLibCheck` basically instructs typescript to ignore declaration files
so if library A depends on library B and library B breaks their API, you wouldn't know about it
it can actually happen, [here](https://github.com/testing-library/jest-dom/pull/150/) you can find a small but real example

**Comment by ranyitz** [comment]
We currently have 3 drawbacks when `skipLibCheck=false`

1. Builds are taking longer and also type check libraries that aren't being used in the app's code.
2. When there is a type inside of a `@types` directory which takes time for TypeScript to check it can cause a heap out of memory exception.
3. When someone releases a bug/unsupported feature in a `@types` library which is not necessarily used in the code, type check fails.
4. The solution for the problem is usually not in the code (you can maybe workaround to make your build pass, but a proper solution would be in the lib itself)

While those problems are real (I witnessed all of them in the past) and disturb the developer's everyday life, the problems of having `skipLibCheck=true` are rare and small.

[From the introducing blog post](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#new---skiplibcheck)

> For example, if a non-declaration file augments a type declared in a declaration file, errors may result that are only reported when the declaration file is checked. However, in practice such situations are rare.

We can also look at the next two big toolkits and see that they suggest on `skipLibCheck=true`
[nextjs tsconfig for users](https://github.com/zeit/next.js/blob/3f691eaa45e8f802f9977ff050f66ac64f016e74/packages/next/lib/verifyTypeScriptSetup.ts#L138)
[cra tsconfig for users](https://github.com/facebook/create-react-app/blob/30fc0bf5ed566d9b42194d56541d278013d7928c/packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js#L104)

**Comment by ranyitz** [comment]
I've opened a PR to configure `skipLibCheck: true` on templates - #2067
