### ISSUE TITLE
classname mismatch for css-modules (SSR)

### ISSUE THREAD

**Issue by mykas** [wix/yoshi#1977]
# 🐛 Bug Report

Related to this feature request:https://github.com/wix/yoshi/issues/1902

### 🔦 Context

We are planning in wix-style-react to drop `import-path` support on next major version which means imports like `import Something from 'wix-style-react/Something'` would stop working. What we will support is basically `import { Something } from 'wix-style-react'` which will give a posibility for our users to consume our es modules based components.

I've tested named-imports on @nitayneeman generated project called: [wix-style-react-mobile](https://github.com/wix-private/wix-style-react-mobile) which uses simple SSR to generate html markup and css for initial page. He used `enhancedTpaStyle:true` to make stylable ouput the css too.

### 😱 Problem

Previously our imports were commonjs only solution so no problems occurred when React.renderToString attached classnames to html and webpack  rendered the classnames stylesheets,
but now I've tested with named-imports and this is what we get:
```error
Warning: Prop `className` did not match. Server: "_-node_modules-wix-style-react-dist-src-Box-Box__root__3wDCc _-node_modules-wix-style-react-dist-src-Box-Box__horizontal__VpebB _-node_modules-wix-style-react-dist-src-Box-Box__middle__KW85s" Client: "_-node_modules-wix-style-react-dist-es-src-Box-Box__root__bjtF6 _-node_modules-wix-style-react-dist-es-src-Box-Box__horizontal__2lMkn _-node_modules-wix-style-react-dist-es-src-Box-Box__middle__3WiyU"
```
> Notice: `dist/src` and `dist/es/src`  and also hash names.

What happened:
1. React.renderToString picks commonsJS modules from wix-style-react package.json and attaches classnames accordingly.
2. Webpack generates classnames in app.stylable.bundle.css and app.css by picking es modules 
3. Consumer gets html rendered with classnames from commonjs and css files that are rendered from es modules. We get classname mismatch and React throws an error in console saying that there is a classname mismatch from server and client side.

This is currently a blocker for us to drop `import-path` imports on next major version. 

### 💁 Possible Solution 

We know that stylable part is handled by StylalbeWebpackPlugin and there is nothing I guess you guys can do here. Stylable team promised us to fix this soon and patch it to version 1.

The other part is css-modules. In wix-style-react we have many sass based css. Possible solution for this part is to force css-modules to generate same classnames regardless of environment. 

### 👣 Steps to Reproduce 

https://github.com/wix-private/wix-style-react-mobile

1. Clone the repo
2. Checkout to named-imports
3. Install node modules
4. npm start
5. Navigate to localhost:3000/ssr

### 🌍 Your Environment

```
"yoshi": "^4.0.0"
```

cc @shlomitc

**Comment by shlomitc** [comment]
Putting stylable aside, this sounds to me like a general issue for any SSR project using "css-modules" out there and we should just adopt the best-practices on the web.

@ranyitz - are you familiar with some approaches?

**Comment by ranyitz** [comment]
> ...This sounds to me like a general issue for any SSR project...

@shlomitc @mykas 
That's a great point

1. **Yoshi does not support SSR** - We're willing to add options like [the one proposed here](https://github.com/wix/yoshi/issues/1902) if you'll contribute them, but we don't have the capacity to solve SSR related problems right now. If we'll support SSR, which will probably be a part of yoshi's future, it will include, testing, docs, template and solutions to every bug/feature request you'll experience :)

2. Adding support for tree-shaking is cool, but what are the business benefits of supporting this. See https://twitter.com/dan_abramov/status/1017110538067857411 And also https://twitter.com/dan_abramov/status/1017110910933094419.

**Comment by shlomitc** [comment]
@ranyitz - I think the issue Mykolas is facing is not only about tree shaking but rather the usage of "esmodules" in the server.

`import {Box} from 'wix-style-react'` will be interpreted differently in the client and in the server:

Server: `wix-style-react/dist/src/Box/index.js`
Client: `wix-style-react/dist/es/src/Box/index.js`

The class names hashes for `.root` in `Box.scss` is derived by the path it is taken from:
Server: `_-node_modules-wix-style-react-dist-src-Box-Box__root__3wDCc`
Client: `_-node_modules-wix-style-react-dist-es-src-Box-Box__root__bjtF6`

**Comment by ranyitz** [comment]
@shlomitc I understand the technical problem. My question is, what is the value of adding tree-shaking support to `WSR`? I just want to verify that we don't invest too much effort over a nicer syntax.

**Comment by mykas** [comment]
Hey @ranyitz, actually the whole effort is not only about the tree-shaking. We need es-modules infrastructure to have support for dynamic imports.

If we dont support named-imports - we basically say that we will only support one kind of modules. Either commonjs or esmodules. 

If we support just esmodules: 
This will be bad for our consumer because most of them run unit tests with jsdom and they need commonjs. 
If we support just commonjs:
We looses ability to use dynamic imports in our codebase. 

The tree-shaking part comes as a side-effect for this.

**Comment by mykas** [comment]
And regarding Dans tree-shaking comments just check this out to which tweet did he reacted: https://twitter.com/dan_abramov/status/1017109672946479104?s=21

Thats exactly what we want to do: code-splitting. 

I believe Dan is skeptical about tree-shaking is because it is so limited in dead-code elimination and works on certain cases. I hope they will continue working on prepack which suppose to be google closure compiler equivalent for react applications. 

Like for example if one of our components uses some external library that only supports named-imports then if we expose our components with commonjs in an old way - it will include for our consumer every single module from that external library even though we use only one.

**Comment by ranyitz** [comment]
> Adding support for tree-shaking is cool, but what are the business benefits of supporting this

By saying this I tried to help you to think on the problem from a different angle. You can still do it if you have the justifications, just keep in mind that you'll have to deal with the problems yourself. I'm saying this because our team doesn't have the capacity of dealing with SSR problems right now, please respect that.

_____________________________
I still want to answer some of the things that you said because I believe it can help you build a better mental model over this problem.

> If we support just commonjs:
> We loose ability to use dynamic imports in our codebase.

> We need es-modules infrastructure to have support for dynamic imports.

As far as I know, you can create a commonjs module that contains dynamic imports.

> Thats exactly what we want to do: code-splitting.

You can have code-splitting without tree-shaking, those are not necessarily related.

> But unfortunately this only works for direct dependencies. If you use cool-lib-from-npm which depends on lodash you have to rely on 🌳-shaking

The `cool-lib-from-npm` should specifically use `lodash-es` for this to work, and in case this library wrote the following:
```js
import { head } from 'lodash-es';
console.log(head);
```
You will only get the `head` function and all of its dependencies in the code, you won't get `chunk` or `compat` for example. (**even if you are writing a commonjs lib and require another library which contains this code**)

> Tree-shaking benefits our consuners when one of our components uses some external library that only supports named-imports then if we expose our components with commonjs in an old way - it will include for our consumer every single module from that external library even though we used only one.

In most cases, you can write your own code differently and have the same benefit.

How many libraries you have that "only supports named-imports" meaning, specify `"sideEffect: false` in their `package.json` and have an `es` directory but not exposing the same thing like lodash (e.g. `library/exported-func`)? For lodash for example, you could just `import compat from "lodash/compat"` instead of `import {compat} from "lodash"`
___________________________

If you believe that the only way would be to provide two directories (`es` and `cjs`) then one possible solution would be to replace the `"/es"` directory path in the css-modules hashing algorithm as `""` so the hash will be the same. Most users that do SSR in Wix (even though we don't provide any support for it) are using the `yoshi-runtime` legacy package, you can see that it is not part of our monorepo and our team does not manages it - https://github.com/wix-private/fed-infra/blob/3ea4813a2c12f2d6db284e7768771e6a9b9f70b9/yoshi-runtime/index.js#L24
