### ISSUE TITLE
[RFC] Yoshi flow editor: Serve editor and settings apps

### ISSUE THREAD

**Issue by yavorsky** [wix/yoshi#2013]
Hey guys, we are working hard on new editor flow and for now I want to see some comments related to serving editor and settings apps.

From what I got, a lot of teams, who working on out of iframe apps has own solutions for it. We'll try to go through pros and cons of getting html files from cdn and compare it with serving settings and editor apps by app developers.

### Get html files from cdn
<img width="1596" alt="Screen Shot 2020-02-25 at 12 48 28 PM" src="https://user-images.githubusercontent.com/1521229/75240560-2fcb8280-57cd-11ea-83e1-f8f08850eb55.png">

The easiest one. Currently, our flow is not support any html files output. So people generating it using custom scripts from vm files. This is obviously bad:
 - users should spend some time on writing html generators.
 - spreads a lot of similar, but not reusable implementations
 - it's not documented

If we understand that this solution is working and optimal for everyone, we can add support to yoshi flow. I had a chance to play around it in feature branch: https://github.com/wix/yoshi/commit/2d89ba5987aacd6c981f5f5f2285c768139e7ea0

I can see some props of this idea in general:
- It's simple. The same way we are providing viewerScript bundle as a file, we can provide editor and settings html files.
- Easier to configure. We don't need to configure fryingpan, etc.
- Faster builds. Since we don't have any docker steps, the CI builds will take less time.
- (debatable) Getting html files from CDN is faster than receiving response from singe server configured via k8.

Cons will be:
- Less control over flow. Serving the app by ourselves gives us more control: load experiments before and serve stuff according to it, load translations.
- Flow is a bit different between local development and prod. To enable HMR, we need to have a local server. For prod, it will be just html.
- e2e tests. Could be really hard to make an e2e tests having just html files.

### Serve apps using node server infrastructure
<img width="1630" alt="Screen Shot 2020-02-25 at 12 47 47 PM" src="https://user-images.githubusercontent.com/1521229/75240537-28a47480-57cd-11ea-83f1-a5bf5982b7d4.png">

Obviously pros here will be cons from html solution. I will just add that experience should contain less boilerplate. We can hide everything related to platform and server from the flow. We can generate Dockerfile and other node related stuff during the build and hide it as much as possible.
User will just GA the app. Experiments, translations, etc will be passed to the Widget the same way for viewer and editor cases.

I see that some of teams (like stores) using scala server to render editor and settings apps. In this situation moving to our server will be much better, since people who developing ooi apps can control server part also.

But in terms of using html vs render app on own server it would be really interesting to hear some comments. In future we can also consider using serverless for this thing, which will reduce number of cons of using own server. Build time won't be reduced and flow between local and prod development could be pretty the same.

**Comment by sdoomz** [comment]
I like the idea of creating index.html during the build phase and putting it to the statics folder. 
In this case, you don't even need to think about the server and all your client app is loaded from a CDN. 

IMO, pros are:   
1. Content is delivered a bit faster. Because of DNS resolution and zero server processing time. 
2. Reliability.  CDN is quite stable and doesn't require additional monitoring tools or health checks. 

On the other hand, global variables as `__STATICS_BASE_URL__` are still injected and it's possible to output `index.html` file either with `app.js` or `app.min.js` based on your `NODE_ENV`. 

In Search App we used a similar, but less flexible, approach - [just html file](https://github.com/wix-private/site-search/blob/master/packages/search-results-widget/src/editorWidget.html) and it took us some time to implement it. 

Summarizing everything, it would be really nice to have this behavior implemented in the new `editor-flow` out of the box. It sounds even better taking into account the fact that this behavior is optional and devs can decide on their own which approach to choose. 

Thanks Artem.

**Comment by bordi** [comment]
Agree with @sdoomz. 

We're (Challenges OOI) using the approach with static `html` files served from CDN and for me, it's quite convenient and easy to setup. 

The only cons I can see so far – you can't serve different bundles for mobile/desktop settings/editor applications which you can do with your own server. 
In our case - different in bundle size would be not so significant and we can live with it.

Good job Artem!

**Comment by bodia-uz** [comment]
As I remember we had only one issue with the static approach. It's using [Client Spec Map Experiments](https://github.com/wix-private/meta-site/blob/master/wix-meta-site-server/app-store-service/client-spec-map-experiment-server/README.md#add) for local development of the editor part. 

For example here is our config for the static override for local dev:
https://bo.wix.com/client-spec-map-experiment-server/experiments/specs.search-site.SearchResultsWidgetOOI_local/1484cb44-49cd-5b39-9681-75188ab429de
With the server approach, we could use this experiment while rendering HTML.

It makes dev life a little bit harder because we have different possible approaches for local development, but overall I think **the pros of static are more important** then cons.

**Comment by sdoomz** [comment]
@bodia-uz you are right, we can connect Client Spec Map issue with
> e2e tests. Could be really hard to make an e2e tests having just html files.

It would be really nice to be able to override `index.html` path via site URL parameters, in the same way, it's already done for viewerScript and viewerWidget bundle. Because currently, I'm not sure will the sled replace your index.html for you

**Comment by yavorsky** [comment]
>It would be really nice to be able to override index.html path via site URL parameters, in the same way, it's already done for viewerScript and viewerWidget bundle. Because currently, I'm not sure will the sled replace your index.html for you

It won't. Today I've played with it, but editor is not overriding anything using both
- Static override (cancelled requests)
- Client Spec Map Experiments

I really like approach to not having 2 apps (local + prod), but override it by just enable some experiment configured via CSM..

I'll try to find someone responsible for it + push someone to fix it if it's possible. Also would be good to create an RFC about best ways to work on editor apps in prod environment locally.

**Comment by ranyitz** [comment]
> Also would be good to create an RFC about best ways to work on editor apps in prod environment locally.

From a comment to reality - https://github.com/wix/yoshi/issues/2043
