### ISSUE TITLE
Missing dependency on node_modules reinstall

### ISSUE THREAD

**Issue by egidijusj** [wix/yoshi#2053]
# 🐛 Bug Report

### 😯 Current Behavior

I ran the following sequence:

```
npx create-yoshi-app
yarn yoshi build
rm -rf node_modules
yarn
yarn yoshi build
```
Last step failed with

```
// Type error: Could not find a declaration file for module 'vfile-message'. '/tmp/a/node_modules/vfile-message/index.js' implicitly has an 'any' type.
```

### 🤔 Expected Behavior

Reinstalling removed dependencies should be enough to continue building project

### 💁 Possible Solution 

To fix, I had to add missing definition to my project's `devDependencies`:

```
yarn add --dev @types/vfile-message
```

### 🌍 Your Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 73.0.1
  npmPackages:
    @storybook/core: Not Found
    @storybook/react: Not Found
    babel-preset-yoshi:  4.37.1 
    eslint-config-yoshi:  4.44.0 
    eslint-config-yoshi-base:  4.44.0 
    jest-yoshi-preset:  4.44.0 
    storybook: Not Found
    tslint-config-yoshi:  4.32.0 
    tslint-config-yoshi-base:  4.22.0 
    typescript: ^3.7.5 => 3.7.5 
    webpack:  4.42.0 
    yoshi-config:  4.43.2 
    yoshi-helpers:  4.43.2 
    yoshi-runtime:  1.0.701 

 Zero config 🛴

```

**Comment by ranyitz** [comment]
@egidijusj Which type of templates did you choose after running `npx create-yoshi-app`? (client/fullstack/library)

**Comment by egidijusj** [comment]
@ranyitz  `client`

**Comment by ranyitz** [comment]
The broken `@types/vfile-message` dependency is installed due to and old version of `stylelint`, which is provided by `yoshi`

Updating the major version of stylelint would be a breaking change, but when looking at it again, Yoshi doesn't provide it under `yoshi lint` and therefore I think that it would be ok to remove it from the installed packages for users that doesn't use it - https://github.com/wix/yoshi/pull/2062

It will effectively fix this issue.
 
![image](https://user-images.githubusercontent.com/11733036/76208856-2f89a900-6209-11ea-851d-14361f4483d3.png)

Just so it'll be clear, this problem is not reproducible when installing with `npm`. Only when using `yarn`.
