### ISSUE TITLE
Bundle size dashboard

### ISSUE THREAD

**Issue by Gongreg** [wix/yoshi#2155]
# Bundle size dashboard

Create some centralized dashboard which shows:
* bundles sizes of all applications/widgets. 
* all of the benchmark result of all of the applications/widgets

so that we can easily look at all data and understand where we need to improve.

# Investigation

## Webpack Bundle Analyzer

To get the sizes of bundles we could use already existing yoshi functionality (`yoshi build --analyze`). It gives us additional information about the bundle that we could later on track.

The time implications of using this plugin are small (10-20 additional seconds), the output that is generated shouldn't be more than few MB. 

There are few possible ways we could use it:

* Generate html output that we upload with relevant build information to the server. This would be the quickest win since it would also solve the rendering part in the dashboard. We just upload html, build info and simply render the html in the dashboard.

* Generate json that we save and then render ourselves. A bit more involving process, but would allow us to store information in a more accessible way. I couldn't find a renderer which would understand this output, so we would have to do additional work to support it.

## Webpack Stats Plugin

As an alternative we can use webpack stats plugin. This plugin allows us to reach all of the data that we want out of the webpack stats object. The plugin is also quite performant and quickly writes information to the json output (While checking I didn't feel big differences in duration). Also it is flexible and we can choose which information we wish to save. It is important to only save relevant information because the stats object itself can be over few hundred MB in a bigger project.

The negative sides are that using this plugin would involve biggest amount of work. Also it only return bundle sizes from the webpack stats, it does not show gzipped size (which is done by analyzer).

Overall it feels like just uploading html output to be displayed from dashboard is a fastest solution and a quickest win. Later on we could decide what additional information we wish to get out of stats.json and use WebpackStatsPlugin for that. 

## Build duration
There is something fishy happening while using `yoshi build --analyze`, it does not allow for the build to finish even when the  Webpack Bundle Analyzer plugin is removed. This didn't allow me to do proper comparison. Now I found that by skipping --analyze the build properly finishes, so we can do a full comparison if it is needed. But overall the difference was about 10-20 seconds on a 90 second build.

**Comment by ranyitz** [comment]
@Gongreg This is a great idea.

I think I have an idea how it's can be done:
1. We can upload all webpack stats from all builds to the CDN. How? We'll just emit them in `dist/statics` and they will be there.
2. [Webpack bundle analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-cli) can accept webpack stats rather than be used as a plugin. We can have a server that accepts an `artifactId` and an `artifactVersion` runs the bundle analyzer on webpack's stats and returns the `html` to the client.
3. Enhance this with a nicer UI that enables you to search for projects
4. If we'll see that it takes time to get the analyzer output we can leverage caching.
5. We can use different analyzer and have different visualizations of the stats, all from one place (by not being coupled to a specific analyzer output)

If you think that this could work, let's verify that creating the stats doesn't slow builds (it shouldn't but it would be nice to verify) and then emit the stats for every build.

Let me know what you think.

**Comment by Gongreg** [comment]
Sadly creating stats slows down Webpack tremendiously. In one of the projects default stats.json output was almost 500mb. There would be a need to only output necessary info, instead of outputing everything that webpack wants to output.

Emitting stats increased build times by few times, the 90s project became around 300s.

**Comment by Gongreg** [comment]
I am investigating https://github.com/FormidableLabs/webpack-stats-plugin to see if the stats output is better.

**Comment by Gongreg** [comment]
Hey @ranyitz , I've checked out the stats plugin and updated the top comment. Thanks for the recommendation, it is definitely working better than analyze plugin if we wish to use `stats.json` . I wrote down 3 possible solutions atm, tell me what you think about them. Lets keep in mind that we wish to get working solution ASAP. :)

Have a great weekend!

**Comment by ranyitz** [comment]
@Gongreg Thanks for checking it out, and nice research! I'll add my thoughts.

## Facts

1. `gzip-size` created by `webpack-bundle-analyzer` is only estimated and not 100% correct, see https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/61#issuecomment-290634958 

> Likewise, the gzip size is calculated by reading the actual compiled bundle files and running gzip for each one of the module sources separately. Thus the gzip size shows you the size after minification and gzip, but it isn't a 1-to-1 mapping with the actual file sizes as gzipping each module separately yields less "wins" in terms of compression as the separate sources have less opportunities for gzip to compress together.

The full gzip size of the bundle is preserved overtime by Perfer, here we care about the breakdown of the modules, which guaranteed to be 100% correct.

2. From what you're saying, the **Time of writing the stats is negligible**.
3. **There is no storage problem** (that I know of) and lowering down the size of the stats file is an optimization we can do any day. (We can have the full stats on the initial version, and then continue and reduce sizes)

## Opinions
Saving `html` after each build is something that I would prefer not to do, I want the build artifacts to be abstract enough so other tools will be able to use them and create everything. For example [this visualization](https://chrisbateman.github.io/webpack-visualizer/) and any future visualization that will be create by anyone!

Keep note that every bug in the process will need be patched to a yoshi version. This means it wouldn't get to everyone at the same time and it'll be harder to patch fixes and features to it. Using something like that `stats` will enable you to do much more without changing anything in builds, and you could take past builds as well.

Every bug in the process can break all builds in Wix and therefore needs to go through a hard review which in reality, will make this process a bit slower and can shift the burden of handling the bugs to the yoshi team (instead to the server/team that deals with the bundle breakdown visualization/search/hosting/alerts and more).

## Ideas

I want to throw another direction here, there is something that is already in the CDN for every bundle ever created in Wix, which we can maybe use to breakdown bundles and do an analysis of the modules inside it:

**Sourcemaps** 🎉 

See the [sourcemap-explorer](https://github.com/danvk/source-map-explorer) and [bundle-wizard](https://github.com/aholachek/bundle-wizard) which I think can be easier to achieve as they don't require any change in build/storage/build-time and uses a resource we already have after each build.

## Summarize

As a first step, I would explore the source-map based solutions as they are the lowest hanging fruit, and you already have all the artifacts in place (we wish to get working solution ASAP)

As a second step I would try to see which benefits I have for the "stats" based solution, and if there are, I would write them as well and create [more types of visualizations](https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d) in the dashboard

If we see that the stats are heavy on the CDN/storage, we can pick specific important fields and by that lower the size of the stats. (As an optimization)

@cowchimp, @Schniz & @deanshub This is your domain, and I think you'll be the first to use the `stats`/`sourcemaps` based solution. Please share you opinions

**Comment by deanshub** [comment]
Great idea using `sourcemaps`, it's a great start, but I would still like to have `stats` since there's a lot more information there which is really important for our tooling (current and future).
In order to have relevant insights, stuff like externals, third parties and the dependency graph are a must.
Even if you can support it partially (allow opt-out) I would still like to have this.

**Comment by Gongreg** [comment]
I tested out communities build:

Here are the build times with different setups (it is a really big build but it will also be an user of this functionality, so we have to have implement a well scaling option):

Default build: ~85s (while running locally, not really relevant since sourcemaps are created in CI).
with Webpack Bundle Analyzer creating html: ~90s (html output around 3mb)
with Webpack Stats Plugin: ~95s. Stats output is close to 370mb.
SourceMaps: ~100s. Running the tool Source Map Explorer to build html took around 45 seconds.

I also checked out cashier (smaller project).

Stat writing duration was neglible, stats size - 32mb.

Overall I am leaning on just using stats from the very beginning. If we are already thinking that we will want to use stats in the future and the other options are also not something that we can do very quickly, we might as well implement things the way we wish in the first place.

We could make sure to have an ability to choose which parts of stats we wish to save in stats.json that we could change without releasing new yoshi versions. This way we will be flexible with what tools we wish to use to render stats/only send the relevant parts in bigger projects.

**Comment by ranyitz** [comment]
@Gongreg Just so it'll be clear. I didn't understand all of the benchmark data, so I rephrased it a bit, can you please add the right timings for the missing places?

### How processes affect build time in CI for applications in Wix?

**Build time of communities nowadays**: `~85s` 
**Build with bundle analyzer creating html (without stats)**: `~90s` [+`5` seconds]
**Build with emitted stats**: `~95s` [+`10` seconds]
**Build with sourcemaps**: `~85s` (already emitted in the base timing) [+`0` seconds]

### How much time does it take to generate nice Graphs from raw data?

Important to say that this category has no affect on build times of developers in Wix If we'll do it in a dedicated server. This server will allow flexibility in the graphs that we're creating, will not cause builds to fail due to bugs in it and will not extend build time in a second. 

**Generating bundle Analyzer `html` using stats:** ?
**Generating Source Map Explorer `html` using sourcemaps:** ?

### Who runs our code?

> We could make sure to have an ability to choose which parts of stats we wish to save in stats.json that we could change without releasing new yoshi versions. This way we will be flexible with what tools we wish to use to render stats/only send the relevant parts in bigger projects.

This should probably be a package install and run in the CI scripts (@illBeRoy) As it's not needed for local development and it will enable @Gongreg to provide new versions without being coupled to specific Yoshi versions.

**Comment by tqmukas** [comment]
@ranyitz I think stats generation has to be a part of the original bundling with Yoshi. Otherwise it might take more than 5 seconds to generate the stats mainly because of the cold start. Standalone solution might also require duplication of webpack configuration and might be not that accurate in the future as it gets out of sync of the original configuration.

IMHO the best way is to have Yoshi generating stats every time it builds a projects in CI and save it near the project (`./stats/stats.json`). For a smaller stats file, Yoshi could pull in a separate configuration (separate schema file) which would tell what the exact fields it needs to generate in the stats. This way we can expand the amount of fields (data) in the future without people needing to update Yoshi. In addition stats probably should be saved outside the `dist` folder otherwise the package size might increase and slow down the deployment.

**Comment by ranyitz** [comment]
@tqmukas I agree.

Generating the stats on every build is something that I think would be the right thing to do. I also agree that we probably want to build the stats to a directory which is both git-ignored and not uploaded to the statics by default (like `dist/statics`).

So the contract between Yoshi and it's users is the when running `yoshi build` on CI it will generate `stats` file in some directory.

_______________

The next step should be a function that runs automatically in the CI. (As a build step)

If it sees the generated stats file, it takes it, does some post-processing with it (which is preferably just picking fields that will lower the size of it) and write the file to `dist/statics` or saves it in a database (or whatever needed).
_____________

That way we could have full flexibility in and separation of responsibilities between the 2 tasks.

cc @ronami Maybe we would use a similar strategy to lower the deployment time of thunderbolt. (I know that it's a different use of the stats)

**Comment by Gongreg** [comment]
Ran, that is a great summary of the way we discussed it, and I feel quite confident about this plan. I am trying to contact CI team to make sure that they are okay with creating stats files in builds.

Thank you for all the insights @ranyitz!

**Comment by Gongreg** [comment]
The initial version is up and running!

**Comment by ranyitz** [comment]
Awesome! https://bo.wix.com/bundle-stats-board/

**Comment by amitdahan** [comment]
This is soooo good!
