### ISSUE TITLE
[proposal] create `tsconfig-yoshi`

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#2339]
# 🙋 Feature Request

### 😯 Current Behavior

Every project has it's own independent `tsconfig.json`

### 🤔 Expected Behavior

Projects have `extends` on common `tsconfig.json` with the ability to override it.

### 💁 Possible Solution 

Create `tsconfig-yoshi` package with best-practices.

**NOTE**: all properties that define paths, should be omitted from `tsconfig-yoshi`, cause they will be counted related to `tsconfig-yoshi`, not consumer project's root (https://github.com/microsoft/TypeScript/issues/29172#issuecomment-450966221).

Usage of this package:
```
{
  "extends": "./node_modules/tsconfig-yoshi/tsconfig.json",
  "compilerOptions": {
      "outDir": "./dist/", // mandatory be present for the libraries
      //...overrides goes here
  },
  "include": [
	"./__tests__/**/*"
    "./src/**/*"
  ],
  "files": [
    "./node_modules/yoshi/types.d.ts",
    "./node_modules/jest-yoshi-preset/types.d.ts",
  ],
  "exclude": ["node_modules", "dist"]
}
```

**Comment by sidoruk-sv** [comment]
As an example (used by our team, so checked on "production"):
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["dom", "dom.iterable", "esnext"],
    "jsx": "react",
    "sourceMap": true,
    "importHelpers": true,
    "downlevelIteration": true,
	"allowJs": true,
	"checkJs": true,
	"noEmit": true, // should be false for CONSUMABLE_PROJECTS
    "declaration": true, // ONLY_CONSUMABLE_PROJECTS_NEED_THIS
    "declarationMap": true, // ONLY_CONSUMABLE_PROJECTS_NEED_THIS
    "removeComments": false, // this should be false to allow webpack magic comments: https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "skipLibCheck":  true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by amitdahan** [comment]
I know we have a different approach for "aligning" `tsconfig.json` files to our needs/recommendations used in the library-flow.
I'm not sure if the two approaches conflict with each other or not.

Would both approaches technically work together? I know we're using TypeScript's own way of importing `tsconfig.json`s. If it follows `extends` and compares the "final" config file - then there's no reason not to also add good defaults by way of a base config.

Just need to make sure the base config applies all recommendations, so there won't be any warnings that are "unfixable".

@ranyitz wdyt?

**Comment by ranyitz** [comment]
We all agree on having a "best practice" `tsconfig.json` configuration options. I think that we do follow `extends` and if we are not, we definitely should.

We are currently using [this](https://github.com/wix/yoshi/blob/6b978323d7942a76f00611a6d2684da8362275f1/packages/yoshi-common/src/typescript/tsconfig-enforcer.ts#L20-L64) as a source of truth, but it's currently only implemented for the Library flow.

On the next major version we would like to add it for other flows as well. It doesn't leave any place for mistakes from the consumer side. We are currently configuring babel for everyone and it works really well. It Configures TypeScript's compiler options and provide good defaults.

If we'll also add a tsconfig package to yoshi's monorepo we'll may use the values  which are in it as "constants" for creating the [this format](https://github.com/wix/yoshi/blob/6b978323d7942a76f00611a6d2684da8362275f1/packages/yoshi-common/src/typescript/tsconfig-enforcer.ts#L20-L64) (In order to prevent duplication)
