### ISSUE TITLE
Can't create project from scratch

### ISSUE THREAD

**Issue by wasabiru** [wix/yoshi#2578]
Hi! I'm trying to create new project with create-yoshi-app by command `npx create-yoshi-app my-app`
But I receive an error `npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wix%2fadd-sentry - Not found`

What I do wrong?

**Comment by amitdahan** [comment]
Hey! 👋 

It seems like you're configured to pull npm packages from the public registry.

Did you follow the fed-handbook guide? Specifically the part that explains how to switch registries:
https://github.com/wix-private/fed-handbook/blob/master/INSTALLATIONS.md#recommended

**Comment by wasabiru** [comment]
No, I have no access to this page. Could you please provide me to page with more information about access and development with wix-style-react?

**Comment by ranyitz** [comment]
@wasabiru While we can (and should) improve the error message, the `create-yoshi-app` tool is internal, and therefore you won't be able to use it in order to generate a project.

You can configure webpack yourself, I this guide explain how https://wix-style-react.now.sh/?path=/story/introduction-getting-started--usage-without-yoshi

If it doesn't work you can open issues on https://github.com/wix/wix-style-react

Closing
