### ISSUE TITLE
Changes in client side code causes the server side to refresh

### ISSUE THREAD

**Issue by dotansimha** [wix/yoshi#324]
# 🐛 Bug Report

### 😯 Current Behavior

Changes in client side code causes the server side to refresh. This causes to discard all in-memory changes in the server side, and makes it harder to persist state in server-side mocks/fakes.

### 🤔 Expected Behavior

Changes in client side code should cause refresh/hmr in client side.
Changes in server side code should cause refresh in server side.

### 🌍 Your Environment

```

  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 67.0.3396.62
    Safari: 11.1
  npmPackages:
    yoshi: ^2.0.0-alpha.2 => 2.7.0 

```

**Comment by ranyitz** [comment]
@dotansimha Thanks for reporting this!

The code that handles those refreshes is [here](https://github.com/wix/yoshi/blob/master/packages/yoshi/src/commands/start.js#L238-L273).

I agree that we would like to refresh the server only if the change is related to the server itself. One solution would be to understand the dependency graph starting from the entry point, and then refresh the server only when one of these files changes.

I would even go further and run `babel`/`typescript` only on those files, but we still need to support a use case of a component library, when you actually need to transpile `js` files even if you don't require them from the server entry file.

Also, if you use `child_process.spawn/fork` you'll need to analyze that as well in order to have the files transpiled/trigger a refresh. Also applied to  `fs.readFileSync` and some more edge cases.

I'm open for ideas/strategies that will make this feature work without breaking all of our current usecases.

**Comment by ranyitz** [comment]
There is an open PR #586
