### ISSUE TITLE
Ability to run a TypeScript file as an entry point on start

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#376]
# 🙋 Feature Request

I use TypeScript. When I do `yoshi start`, I'd like to pass a custom entry point which is based on TypeScript:

```sh
yoshi start --entry-point=./some/entry.ts
```

Obviously, it doesn't work today.

### 💁 Possible Solution 

Preload `ts-node/register` (if needed) in [`app-server`](https://github.com/wix/yoshi/blob/master/packages/yoshi/src/tasks/app-server/index.js#L84) task - smth like this should be working:

```sh
node -r ts-node/register ./some/entry.ts
```

**Comment by ranyitz** [comment]
@roymiloh I agree, and thanks for opening this issue. We would like to run the server code through `ts-node` in development instead of tranpiling it to dist and run it from there. It means we could stop running `tsc` on watch mode (during `start`). This is a breaking change though, so let's add it to yoshi@3.

PR welcome!

**Comment by roymiloh** [comment]
We _could_ stop running `tsc`, but we don't have to - hence, it's not a breaking change:) I suggest to start by running `ts-node` in case of `.ts`/`.tsx` extensions (opt-in feature; does not break anyone).

**Comment by ranyitz** [comment]
@roymiloh Agree, we can implement the `ts-node` feature and release in a minor version.

We just need to remember to disable `tsc` when this feature is on, so we won't transpile twice.

**Comment by roymiloh** [comment]
Relevant for `babel-register` as well.
