### ISSUE TITLE
Add field validation for Yoshi's config

### ISSUE THREAD

**Issue by ronami** [wix/yoshi#500]
# 🙋 Feature Request

### 😯 Current Behavior

If fields that are not supported are used there are no warnings. If fields are used with wrong types weird errors may be thrown.

### 🤔 Expected Behavior

By using [jest-validate](https://github.com/facebook/jest/tree/master/packages/jest-validate) we can have pretty nice errors for using wrong/unsupported types of configuration fields.

**Comment by ronami** [comment]
I think that it's a good place to start but it's just a suggestion.

**Comment by netanelgilad** [comment]
So I think I'll try an initial implementation with `jest-validate` cause it seems very easy to plug in and get going. If it's Good Enough™ (😄) then we can stick with it. Otherwise, another solution I looked into is how `webpack` does configuration validation, and they are using a JSON schema and validating using [`ajv`](https://github.com/epoberezkin/ajv), which is a very mature solution and should be very future proof.

**Comment by netanelgilad** [comment]
@ronami I think i'll run the validation before any command is run by yoshi. But the question is whether we should fail or warn on errors. Cause there may be errors in the config that are not relevant to the command currently being run, so we might fail the command even though it might have succeeded. Thoughts?

**Comment by netanelgilad** [comment]
Just to make sure, I meant that you could have a wrong validation for a field that is only used by the `test` command and not by the `build` command. So the question is whether when the user has wrong configuration for the `test` command, and he runs `build`, should we fail that command as well.

IMO, the whole configuration should be correct no matter what command you are running, cause we don't know how wrong configuration may affect the user in the future. @ranyitz What do you think?
