### ISSUE TITLE
Add proper support for css modules to typescript projects

### ISSUE THREAD

**Issue by iaroslavshvets** [wix/yoshi#506]
# 🙋 Feature Request
Add ability to import scss modules in .tsx files via `import` with proper IDE auto completion hints.

### 😯 Current Behavior
Have to define 
`declare module '*.scss'; ` somewhere. or use `const s = require('./module.scss')` syntax, in any case, auto completion is lost.

### 🤔 Expected Behavior
write `import * as s from './module.scss';`

### 💁 Possible Solution 
Solution is described here. It's basically a drop-in replacement for css-loader:
https://medium.com/@sapegin/css-modules-with-typescript-and-webpack-6b221ebe5f10
https://egghead.io/lessons/webpack-import-css-modules-with-typescript-and-webpack

### 🔦 Context
Using latest yoshi version.

**Comment by ranyitz** [comment]
I think we should consider adding this plugin.

**Comment by netanelgilad** [comment]
IMHO the preferred solution would be https://github.com/Quramy/typed-css-modules. This solution is outside the build system, which may be a downside because it means the user has to run it themselves, but I actually think that is what makes it better. I don't know in what ways the other plugin may affect the build process, and what bugs it may introduce.

We can consider adding this process somehow to `yoshi` but without affecting the build process. @iaroslavshvets would you consider trying out https://github.com/Quramy/typed-css-modules manually in your project and let us know how you find that solution?
