### ISSUE TITLE
Remove depCheck from `yoshi start`

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#514]
# 🙋 Feature Request

### 😯 Current Behavior

`yoshi start` runs the depCheck task in order to check dependency versions using depKeeper.

### 🤔 Expected Behavior

`yoshi start` should not run this task.

### 🔦 Context 

Dependency version checks should only be run at `yoshi build` time as we do not want to get in the way of the development process.

**Comment by netanelgilad** [comment]
A layman's question: are developers supposed to run `yoshi build` on their local machines or is it practically run only on CI? If only on CI, then maybe it makes since to add an npm script of `depCheck"`cause you might want to check your out of date deps without building. (probably should be another issue).

**Comment by yairhaimo** [comment]
We run `build` as a `pretest` hook:
```json
"scripts": {
    "start": "yoshi start",
    "precommit": "yoshi lint",
    "pretest": "yoshi build",
    "test": "yoshi test",
    "posttest": "yoshi lint",
    "release": "yoshi release"
  },
```
