### ISSUE TITLE
Add Yoshi Analytics

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#531]
# 🙋 Feature Request

### 😯 Current Behavior

Today we are blind to how our users use Yoshi. We dont know if they encounter any errors, which commands they use, how long does each command take (per project), bad usages, etc.

### 🤔 Expected Behavior

We should have a dashboard with information about Yoshi's usage by our customers.

### 💁 Possible Solution 

@ronami started working on error reporting at https://github.com/wix/yoshi/pull/373.
We will have to enhance this POC with usage data.

**Comment by netanelgilad** [comment]
@yairhaimo @ronami @ranyitz  I'm trying to better define the scope for myself, so I can avoid over/under-engineering a solution. This is my interpretation of the definition, please let me know if there is something to be added/dropped. And sorry for the hafira 😊 

### Scope

Gaining insight into improving `yoshi` as a tool by tracking the usage of `yoshi` in different ways.

### Out of scope

* Tracking insights that are relevant for the users and not for `yoshi` itself (like build sizes, long test run times, etc..)
* Insight into the distribution of `yoshi` across the organization.

These considerations should be considered by themselves.

### Problems to be solved

* Feature prioritization - We would like to gain insight into the diffrerent features of `yoshi` so we would be able to better prioritize any feature requests/changes. This should also affect the deprecation process of features as they become outdated/unused.
* Which environments to support - When implementing features, we would like to have them supported on the different environments that are users use. An environment can be any data related to where yoshi is running: OS, node version, CI/local.
* Detecting performance problems - Though this could be solved more properly using some kind of performance tests (which are out of scope for this issue) we can also gain insight into the performance of `yoshi` in **real world projects** and prioritize needed improvments accordingly.
* Error tracking - Apart from insights into features, we would also like to know about errors encoutered by `yoshi`. This should allow us to be proactive in detecting and solving issues, and prioritize bug fixes based on data.

### Concerns to track

* Usage - Tracking usage will give us insight into the different features yoshi provides. Some of the things we would like to know about the usage are:
  * Commands used -  Tracking which commands ran and with what arguments. This should allow us to have better deprecation process for certain commands and flags.
  * Configuration used - Tracking any custom configuratiuon used by the user. This should also allow us to gain insight into feature usage, better prioritization and deprecation.
  * Generators used - Tracking which generators are used. Also insight into feature prioritization.
* Environment - We should track the environment of `yoshi`'s exectution and attach that data to relevant events. (Does it make since to have events to just track the environment?)
* Performance - Tracking the execution time of different phases of `yoshi`s execution:
  * Tracking each command execution time. Will give us an overview of `yoshi` performance and which commands should be optimized.
  * (?) Tracking more specific phases in the commands like transpilation time, warmup time, etc...

### Consuming analytics

We would like to consume the analytics in an easy to use dashboard, where we can keep track of certain metrics, and consult the dashboard when we need to make a decision based on data. Considerations:
* We need to support analytics at least 1 year back. (a number I came up with, suggestions welcome)
* Protected dashboard with team access. Possibly with public view only mode? (Not really important, but may be a bonus if want to allow are users to explore the data.
* No need for real time tracking (Unless I miss something, I don't think it's important for us to know of events as they happen, and a certain delay until the data is available to us it OK).

### Security

Two obvious considerations when it comes to security is to collect purely anonymous data and a noticable and easy opt-out. If the data collected is truly anonymous and we don't care about having a public view of the data, then the security consideration of the storing of the data can be relaxed.

### Implementation considerations

* Should not have an observable performance overhead. Some performace overhead is inevitable, but it should be kept to a minimum.
* A failed attempt at tracking events **must not** fail the current running process. Analytics is secondary to the success of a `yoshi` command.
* Prefer not to bring our own implementation of a tracking package. 😸

**Comment by yairhaimo** [comment]
Great writeup!

Some thoughts:

- This should be treated as an internal tool so no need for any external facing features.

- > Performance - Tracking the execution time of different phases of yoshis execution:
Tracking each command execution time. Will give us an overview of yoshi performance and which commands should be optimized.

  If we collect this data we shouldnt aggregate it because it has a large variation across projects and the values wont tell us anything (build takes 40s on average, is that good/bad?). Maybe aggregate only for regression testing sake (display time per `major.minor` version).
We can save this data per project for better in-depth drilldown.

- How do we save the results? Some projects will have a lot more data points than others and can skew the results.

- All charts should show current and historic values (per week/month?)

- Additional feature - each drill down should show a breakdown of other selected statistics, for example:
  - Language type chart: Typescript/Babel 
  - Drilldown into Typescript: Show split between Yoshi versions, Split between project types (client/fullstack)

**Comment by netanelgilad** [comment]
> If we collect this data we shouldnt aggregate it because it has a large variation across projects and the values wont tell us anything (build takes 40s on average, is that good/bad?). Maybe aggregate only for regression testing sake (display time per major.minor version).
We can save this data per project for better in-depth drilldown.

That is a great point I haven't fully thought out. Just having general build times isn't really helpful, but tracking the changes in build times for the _same_  project should give us insight into performance changes. But creating a view for every user's project doesn't make sense. I'm trying to think how this could be implemented in a way that is easy to consume.

> How do we save the results? Some projects will have a lot more data points than others and can skew the results.

Relates to the previous point IMO, and solving this point should help us solve the other one.

**Comment by netanelgilad** [comment]
@yairhaimo Do you think we should change the scope of this issue to only error reporting and open new issues as we work on other parts of the analytics? Otherwise I guess this issue will not be closed any time soon (which could also be ok).

**Comment by ronami** [comment]
Merged in #612.
