### ISSUE TITLE
Presence of `README.md` should allow to create a yoshi app

### ISSUE THREAD

**Issue by roymiloh** [wix/yoshi#541]
# 🙋 Feature Request

Presence of `README.me` should still allow me to create a yoshi app.

### 🤔 Expected Behavior

Filter out `README.md` from files check and **not override it**.

### 🔦 Context 

It's pretty common to create a repo on GitHub with a README.md file included / write a README.md file beforehand (... before creating the actual app, API first etc.). I don't see any point to throw an error in case of its existence.

**Comment by ranyitz** [comment]
@roymiloh Thanks, PRs welcome!

**Comment by Schniz** [comment]
Hey @roymiloh, sorry for the inconvenience but we've decided to close the PR implementing this feature request due to the reasons described in https://github.com/wix/yoshi/pull/742#issuecomment-438200670.

I'm going to close this issue as well, but if someone thinks that I'm wrong, feel free to reopen and discuss about it 😸 
Anyway, thanks again for filing the issue!
