### ISSUE TITLE
TypeScript support in the codebase

### ISSUE THREAD

**Issue by amitdahan** [wix/yoshi#587]
# 🙋 Feature Request

### 😯 Current Behavior
Codebase is in written in vanilla JS

### 🤔 Expected Behavior
Type-safety heaven

### 💁 Possible Solution
Add `tsc` to the (non-existent?) build chain and configure in a hybrid way to allow gradual migration

### 🔦 Context
Will give better confidence approaching the codebase and hopefully open it for more contributions 💯💯 

I don't mind assisting/doing this.

**Comment by yairhaimo** [comment]
We understand that a type system can be beneficial to ourselves and to external contributors but we're reluctant on adding a transpilation phase to Yoshi.
What we can do is begin using `jsdoc` in order to document our codebase and receive autocompletion with type information but without the transpilation.
You can refer to this document if you're willing to put in the work:
https://github.com/Microsoft/TypeScript-wiki/blob/master/JSDoc-support-in-JavaScript.md

**Comment by yairhaimo** [comment]
IMO flow comment types are more obtrusive than jsdoc comments.

**Comment by amitdahan** [comment]
I'm not sure any of those will give the same kind of confidence TypeScript gives, but I'm probably wrong.
What's so bad in adding a transpilation phase?
I'm well aware of the complex-ness involved but it can be set-up in a way that it's much much simpler than most projects, without involving any of the bundlers out there, it should still be fairly quick to transpile. No?

**Comment by ronami** [comment]
If we're already adding jsdoc annotations we might as well run `tsc --noEmit` and get type safety out of it, similar to how they do it in Webpack.
