### ISSUE TITLE
improve/refactor usage of `unprocessedModules` 

### ISSUE THREAD

**Issue by netanelgilad** [wix/yoshi#600]
# 🙋 Feature Request

### 😯 Current Behavior

Currently we use a function from `yoshi-config` called `unprocessedModules` in some of the loaders to make them work on selected dependencies. The implementation of the function is quite expensive and slow. Also, we are using this function only on selected loaders and not all.

### 🤔 Expected Behavior

First, we need to improve the performance of `unprocessedModules`, as it is a function that runs quite a lot during the build process, and we may gain a performance boost by improving it.
Other than that, there is a case to be made about using this function for _all_ loaders, as the purpose of this function is to select which modules need to be processed by loaders. Though still this is a feature we need to think if we want to opt-in to.

@ronami @ranyitz Share your thoughts and I'll implement.

### 💁 Possible Solution 

1. Write faster code :)
2. Maybe use the function in all loaders

### 🔦 Context 

Issues like #581 may rise for other types of loaders.

**Comment by ranyitz** [comment]
@netanelgilad I've moved it into a file and changed its name to `shouldTranspileFile` - A function that accepts a file path and return true if it needs to be transpiled https://github.com/wix/yoshi/blob/a94fd313546a00ce83f10404c8df639703ed2869/packages/yoshi-common/src/utils/should-transpile-file.ts#L4

Maybe we can use [`include` & `exclude`](https://webpack.js.org/configuration/module/#ruleinclude) instead of this function
