### ISSUE TITLE
Lint Stylesheets by Default

### ISSUE THREAD

**Issue by yairhaimo** [wix/yoshi#661]
# 🙋 Feature Request

### 😯 Current Behavior

We do not currently have linting for stylesheets.

### 🤔 Expected Behavior

We should have linting for stylesheets!

### 💁 Possible Solution 

https://stylelint.io/ is valid solution.

**Comment by ranyitz** [comment]
I think we do have [stylelint support](https://github.com/wix/yoshi/blob/f876b16081f6abb7748a0049edb0d81cc2b81824/packages/yoshi/test/lint.spec.js#L191-L218) but you need to add stylelint config to make yoshi run it.

https://github.com/wix/yoshi/blob/5367d5f58b3c7633d39f4f9b9d3331cee6b73ab4/packages/yoshi-helpers/queries.js#L42-L46

Maybe we'll want to add it by default (starting with adding it to the templates).

Or maybe we would like to have a zero config solution and to give it to everyone.

I would start by adding it to the templates and see some reactions before enabling by default to existing projects (could make it hard for people to migrate)

**Comment by Schniz** [comment]
I'm on it. ✋ 

`stylelint` actually works and it looks like some of our users use that already. I'm going to add a simple package (`stylelint-config-yoshi`) that has some "sane" defaults (which look okay to me): I only have added [rules that can cause bugs](https://stylelint.io/user-guide/rules/#possible-errors). Other than that, there's also `stylelint-prettier` (just like eslint-prettier), which can be used for formatting. But we'll discuss about specific rules in the PR.

If we are taking the course of adding it to the new project templates (as `stylelint.config.js` or whatever), should it be targeted to `version_4.x`? because it isn't a breaking change - it is just a nice addition. 

Taking it to the next level and providing defaults *without the file itself*, however, can be a breaking change.

what do you think @ranyitz?

**Comment by ranyitz** [comment]
@Schniz Great!

I have never worked with it, but if we've checked it on some projects, and we think that it's a good practice, we can add it by default to our templates, which is not a breaking change.

We should look into things like (VSCode, webstorm) IDEs integration, how it will affect the build pipeline etc.

> Taking it to the next level and providing defaults without the file itself, however, can be a breaking change.

In general, it's really good to aim towards zero config. For this specific case, I think that it's a big breaking change, and it could take time for people to migrate; version 4 is already bloated with breaking changes, and even for version 5, will the IDE integration work?

**Comment by Schniz** [comment]
> In general, it's really good to aim towards zero config

There are projects that already use `stylelint`, so I think that if we think that it's a good practice (even starting off with just `prettier` integration), it's a great way to start and get some feedback. If it's too annoying, we can always tell them to remove their configuration file and rethink it. If it works good, maybe it'll be good for version 5.

> We should look into things like (VSCode, webstorm) IDEs integration

Stylelint should work fine on IDEs. VSCode has a plugin and [WebStorm even mentions it in their docs](https://www.jetbrains.com/help/webstorm/using-stylelint-code-quality-tool.html). It also works on my Vim! ✨ magical ✨ 
The only "problem" that it seems to have, is that I need to configure a section in `package.json` to extend my package (exactly like `eslintConfig` for eslint) in order to make my Vim understand which configuration to use. I guess it would be the same both for VSCode and WebStorm

**Comment by Schniz** [comment]
Even when we have `stylelint.config.js`, `yoshi lint --fix` won't fix the errors. Can be added though (probably using the `options` passed to the haste task)

**Comment by Schniz** [comment]
I wonder whether it's better to have a uniform "linter" package, that lints `tslint`, `eslint` and `stylelint` and produce a consistent output, along with `--fix` that works on every file:

```
$ yoshi lint App.scss App.tsx

😭😱 We found some errors! 😱😭 

*ERROR* App.scss (stylelint/rule-name-that-i-dont-know)
    1 | .hello {
  > 2 |   world: green;
      |    ^
    3 | }

*ERROR* App.tsx (tslint/rule-name-that-i-dont-know)
    1 | function welp() {
  > 2 |   callThisAnErrorMyGoodFriend();
      |                              ^
    3 | }
```

I'm not sure if this is a good thing to do, although IDEs will still be able to use the plain `{ts,es,style}lint`, and by using yoshi in terminal they'll have a unified experience. What do you think? is it overengineering? @ranyitz

**Comment by ronami** [comment]
I really like the concept of showing a coherent output for all types of files. That would make Yoshi act like a single tool instead of a few tools stitched together. 🏆
