### ISSUE TITLE
create-yoshi-app external templates support [Guild Week Proposal]

### ISSUE THREAD

**Issue by illBeRoy** [wix/yoshi#694]
# `create-yoshi-app` Platform
Guild Week Proposal
> Roy Sommer, Guy Ben-Aharon

## Goals
1. Introduce `create-yoshi-app` not only as a tool but also as a platform for any group in Wix to use and extend when creating generators for their projects.
2. Lift the burden of maintaining all of the templates from the infra team.
3. The new features will be in addition to existing functionality, so to preserve backwards compatability with existing templates.

## Plan
1. **Requirement**: Support external templates
2. **Requirement**: Provide methods for customizing the project generation process
3. **Requirement**: Add documentation for the above (which is missing right now)
4. **Nice To Have**: Create a repository of non-infra backed templates

### Support External Templates
Allow 3rd party templates to be used with `create-yoshi-app`, as long as they're hosted
on github, e.g.:

```sh
npx create-yoshi-app --from wix-private/business-manager-module ...
```

Things we need to take into account:
1. Some (if not all) templates will be private. We solve that by cloning them using `git+ssh`.
2. Some templates may be part of monorepos. We solve that by allowing to pull specific path from repos (e.g. `wix-private/wixos/some-foo-template-dir`)

### Customizing Generation Process (`yoshiegg.js`)
Some templates will probably require custom inputs \ phases \ actions when being run. We can support that by deciding on some "configuration" file format that tells `create-yoshi-app` what to do. In our opinion, the best approach is to make this file a runnable `yoshiegg.js` (well, the "egg" part is not mandatory but cool imo 🤠) file that can import yoshi methods and exports lifecycle hooks for `create-yoshi-app` to utilize.

Let's say, for instance, that we want to ask a custom question and export its answer into the `valuesMap` that are used by `create-yoshi-app`'s template engine:

```javascript
const { ask, writeValue } = require('yoshi-actions');

// run code at designated hooks in the generation process
module.exports.setUp = function() {
  const routesCount = ask('How many routes do you want in your express app?');
  writeValue('ROUTES_COUNT', routesCount);
}
```

By adding this to the `setUp` phase, the question will be asked right after choosing the template, and before the template engine is being run.

Another example, is extending the default `install` phase (which runs `npm install`) with bower as well:

```javascript
const { run } = require('yoshi-actions');

// support extending on top of the default behavior by giving a "$super" parameter that can be optionally used (just ignore it if you don't want it to run)
module.exports.install = function($super) {
  $super()
  run('bower install');
}
```

Using `js` files means that manifest files can do all sorts of tasks without us having to add support for everything (e.g. fetch some data from a server, or create some files).

We propose the following API:

#### Actions
* `log(message: string): void` - log a message using `create-yoshi-app`'s logger.
* `ask(questions: string): string` - ask a question.
* `fail(reason: string): never` - log a failure message and terminate the task.
* `run(cmd: string): string` - run a shell command inside the working dir.
* `writeValue(valueName: string, value: any): void` - writes a value into the `valuesMap` that is used by the templates engine.
* `readValue(valueName: string): any` - reads a value from the `valuesMap`, such as "authorName".
* `workingDir(): string` - returns the working dir.

#### Hooks
* `setUp()` - if exists, runs right after the user selects the template (or at startup, if using external template).
* `initGit($super)` - if exists, will run instead of the default `initGit` phase.
* `install($super)` - if exists, will run instead of the default `install` phase.
* `lintFix($super)` - if exists, will run instead of the default `lintFix` phase.
* `tearDown()` - if exists, runs after everything is done, right before writing the `success` message.

Things we need to take into account:
1. **Backwards compatability** - preserve default behavior for existing templates. We solve that by not changing anything if no `yoshiegg.js` file exists in the template's dir.
2. Extensive documentation.

**Comment by netanelgilad** [comment]
Great proposal @illBeRoy! This is something that (at least for me) made a lot of sense for `create-yoshi-app` and will be a great benefit for us as maintainers and for our users as well, which will be less dependant on us.

I mostly agree with the plan, and I would like to add one requirement. Without going into implementation of how to achieve it, I think that an important requirement is that we (the `yoshi` team) will be able to continue to provide best practices (at wix and in general) through generators. Generators are our way of letting teams know what we believe is the best workflow, tools and integrations. And if the external templates will diverge from that too much, we will lose this benefit, and IMO it's a must. 

We can probably implement it in several ways. The one that comes to the top of my head is extending a base template instead of only creating templates from scratch. But maybe someone can think of a better idea.

Another important point for me, is to try to avoid over-engineering a solution before we need it. I think the general idea of the proposal with hooks and utility functions is great, but let's try to build the hooks and the functions against a real use case, and not prepare for the future too much. When a new hook will be needed, we can add it. (That doesn't mean that the current hooks and functions are over-engineered. If they hermetically fit the use case we want to solve during this week then they are absolutely fine).

**Comment by netanelgilad** [comment]
We had an internal discussion about this feature, and I'll try to summarize the points here.

We talked about how we can achieve the requirement I've mentioned above, about keeping generators up to date with best practices. We have agreed that it's an important point, but it's probably out of scope for what we can achieve in a week, and the solution would be rather hard to implement currently with no immediate benefit (as the template that is the current use case doesn't need that). So we'll tackle that at another time in the future as the needs become more concrete. 

We've come up with an idea for a solution that may be fitting for the current use case, and will not introduce concepts that we might not need currently. Since we want `create-yoshi-app` to remain about creating apps that use `yoshi` and it's best practices (and maybe more framework-y features in the future), we can extract the generation engine into it's own module that would than be used by `create-yoshi-app` and another tool for other wix apps like `create-wix-app`. We could even open source that engine as `create-x-app` and provide it as an alternative to a tool like `yo`, since we know it is quite complicated and tries to handle a wider set of use cases.

@illBeRoy What do you think? It wouldn't change much of the proposal implementation details (as long as we see that it fits this general engine) and the engine we extract could be a cool open source project that wix maintains.

@ronami @ranyitz @yairhaimo If I mentioned something wrong or you want to emphasize something, feel free to drop in the conversation.
