### ISSUE TITLE
Use add-sentry and add-fedops when generating a new project

### ISSUE THREAD

**Issue by technotronic12** [wix/yoshi#774]
# 🙋 Feature Request
Add sentry and fedops to newly generated projects

### 😯 Current Behavior
It is not adding those two tools

### 🤔 Expected Behavior
New projects should come with this tool by default

### 💁 Possible Solution 
Use the two libraries:
add-fedops: https://github.com/wix-private/fed-infra/tree/master/add-fedops
add-sentry: https://github.com/wix-private/fed-infra/tree/master/add-sentry

### 🔦 Context 
**Add fedops** 
should work without passing any params, it uses the data from package.json

**Add Sentry**
It receives two params, teamName and ProjectName. We can either read them from package.json  (we can use name as projectName and the organization as teamName) or we can ask people if they would like to have a new sentry project created and ask if the name and the team name should be taken from package.json.

**Comment by technotronic12** [comment]
Yo, only saw this message only now.
When a user creates a new client / fullstack project he should have sentry and fedops already pre-configured in the project. Similarly to what we have with new relic both in the scala and node framework.

When speaking about it with @yairhaimo we decided that the best way to do it is to provide a module that does exactly that, adds all of the needed config to a project and this way it can be used both in new and existing projects.

The flow should be that when the user is creating a new project it should come with fedops in it. Sentry, when he is getting asked for the different fields in the generator it should also ask him if he wants sentry to be added to his project. Sentry needs the team name and project name to be added to Sentry website (add-sentry module does it), we should ask him to provide a team name (we can probably use the organization name that you ask for in the generator questions). Project name should be the project name from package.json i guess.

**Comment by Schniz** [comment]
I'm opening a discussion here (after speaking with @technotronic12, @cooperd, @yairhaimo and @ranyitz):

Using `add-fedops` and `add-sentry` inside `create-yoshi-app` is problematic in terms of maintenance, testing, reliability and speed.

In addition to add documentation (which is done in #873), we totally understand how important is to make it easier to integrate error tracking/monitoring. Let's talk about each feature individualy:

## `add-fedops`

This executable just adds a couple of libraries, adds a new file called `fedops.json`, updates the main component definition and the `index.ejs`. basically, modifies static files.

Although it sounds logical to run it on every new template for "code reuse", we won't be testing it in our e2e. And if we would have tested that, it just makes no sense to have it in a different repo.

If we add them to the templates, we'll have to take care and update them for every fedops change. Is it good? Is it something that `create-yoshi-app` should do? Are we willing to move "how to configure fedops" into the app generation project?

That's not hard thing to do, but we need to really understand if this is the right thing to do for the common Yoshi app.

## `add-sentry`

The executable will make API calls to Sentry to get a DSN for a specific `team` and `project`, and if they don't exist - it'll create them. Then, it'll configure the project with the DSN and whatever it needs to be compatible and to report to Sentry.

Running the executable on `create-yoshi-app` can throw errors and make the creation step very slow and less reliable. moreover, it would actually _change things in sentry.io_. What about team-name inconsistencies (that's why I opened #876)? what about project name collisions? should we take care of it in `create-yoshi-app`?

So we have two good options and two weird ones over here (from my prespective):

1. Just tell the users they can use the `add-sentry` package. maybe write something like `santa-doctor`, but for yoshi - like `yoshi audit` (cc @ranyitz). This way we can show that monitoring and error tracking wasn't configured yet or something:
    ```bash
    $ npx yoshi audit
    ✅  Scoped package
    ✅  Monitoring configured
    ❌  Error tracking configured
    ```
2. Integrate Sentry with the templates, by having a DSN property in the yoshi configurations and use that if it exists. This can be generated using an executable from npx (`npx -p @wix/add-sentry generate-dsn`) using fields from `package.json`. This can be documented in Yoshi's website and to suggest it when finishing generating a project in `create-yoshi-app`. We can fail builds/tests if the project lacks the DSN.
3. Have some kind of code transformation on build? this is insane and weird and too much magical
4. Wrapping Sentry with some kind of proxy that will take a `team` and `project` and will convert it to DSN before forwarding it to Sentry. (this is veryyyy error prone, need to take care of registring a new user/team/project, etc)

what do you think?

**Comment by yurynix** [comment]
I think that the goal of `create-yoshi-app`, and every generator in general, is to create an app with the latest "best practices".
So, **if** we decided every project should use fedops and sentry, that's something the generator should handle, IMO.

So, I'm for number (2) on your list, integrate it with the generator, but don't make it modify sentry.io automatically, instead it should tell the user that he needs to go to sentry.io and create a new DSN, then paste it as input to the generator and it'll do the rest.

Number (1) is a good project regardless the above, sounds like a useful tool.

**Comment by technotronic12** [comment]
I have to emphasize whay @yurynix said. As a guild, we decided that the best practice for monitoring client-side apps inside Wix is using Fedops and Sentry.  

It seems that the reasoning about create-yoshi-app as some kind of a generator is what makes this issue complicated, but this is only an implementation detail. In the server guild, you just get a framework project with the latest and greatest in it without asking anyone if he wants to use it, this should also be the case in the FED guild.

**Fedops**:
Because my team controls the add-fedops module and the Fedops project it is easier to make changes to both if something in FedOps changes. So in your case I think it is enough to test that this package was run. It has e2e that uses create-yoshi-app and checks that everything was added as we expected. You can just run it as a black box. It also handles different failures and acts accordingly.

**Sentry**:
I agree that its annoying that add-sentry has to send a request to Sentry in order to create a team and a project, but, currently this is the way that Sentry works (we will file a feature request to have this generation done in code without issuing requests, same as it is done in new relic). 

IMO the generator can ask if Sentry should be added and if yes, then it can ask if to use the organization name as the team name or not (and maybe allow the user to enter a different team name). If the user chooses no he can add it later.

Project creation of duplicate names just names the project as `project-name-{some-letter-value}` in order to handle name collision. add-sentry uses Sentry to monitor its success. I guess I can add a log that if something fails prints it to the user and asks him to do it manually. 

**Overall, failure in addition of one of the tools should not fail project creation.**

**Comment by Schniz** [comment]
Sure, @yurynix and @technotronic12. I agree that we need to make the best practices and make it easy to use them and apply them. The question is - at what cost?

> In the server guild, you just get a framework project with the latest and greatest in it without asking anyone if he wants to use it, this should also be the case in the FED guild.

You are totally right. Building production-grade apps with Yoshi should be as easy as building a production-grade app in the server guild. Yet, I just think whether this is the right approach (generating teams/projects in Sentry for instance). It feels like the server guild uses tools that have the same approach and support this kind of thing.

> It seems that the reasoning about create-yoshi-app as some kind of a generator is what makes this issue complicated, but this is only an implementation detail

I'm not sure about that. When I run a new app, I want it to be fast. Most of the times people run `create-yoshi-app` isn't for necessarily for a production app, and they even use random names for that (`asdf`). Would we want to have a `blabla` team with a `asdf` project? I guess no 🤷‍♂️ 

About Fedops:

> I think it is enough to test that this package was run. It has e2e that uses create-yoshi-app and checks that everything was added as we expected

I'm not sure about that either. `create-yoshi-app` has e2e tests, but it will run some external tool that alters the code after it finishes? This co-dependence between the two libraries just sounds odd to me. I understand that this package is maintained in your team and it's super ideal that it'd work this way, but we own Yoshi and I believe that using another package that changes the project tree is shaking responsibility. Eventually - we'll get issues regarding this situation (and it doesn't matter if it is to bump the package version).

> I agree that its annoying that add-sentry has to send a request ... but, currently this is the way that Sentry works

So I guess we can wait until they'll have a better API? why is it so urgent to do right now? I truly believe that making these kinds of side effects is dangerous and somewhat irresponsible in terms of maintaining the Sentry account. Because again, users create projects for fun, not necessarily for production.

> IMO the generator can ask if Sentry should be added and if yes, then it can ask if to use the organization name as the team name or not (and maybe allow the user to enter a different team name). If the user chooses no he can add it later.

We start to have lots of questions in the generator, and I think it makes everything complicated. What about having `yoshi sentry` command that manages that? do we really need to ask all of these questions in the generator? will the common user even know what we're asking about?
I'm not quite sure and I think the more questions we add (or, the more "configurable" yoshi is) the more problems we have. also - more test cases to verify.

> **Overall, failure in addition of one of the tools should not fail project creation.**

Isn't it odd? why wouldn't it fail the project creation? If I need a production app and it doesn't give me a production app, then why do I toggle and configure Sentry in `create-yoshi-app`?

The reason why I'm asking this question is because this question _will_ be asked, and I got no good reason for it. This delicate type of questions is a problem and somehow gives the feeling of a product that's branching out too much.


I really believe that calling to a simple cli (`npx @wix/add-fedops`) is easy. I think we can verify some things on build, maybe even generate reports - at least until Sentry will be easier and lighter (just like using a `newrelic.json` file)

what do you say?
