### ISSUE TITLE
prepush linting

### ISSUE THREAD

**Issue by hepiyellow** [wix/yoshi#880]
# 🙋 Feature Request

Prepush linting (as opposed to precommit)
- Motivaiton:
  - avoid the (short) wait for linting.
  - Might be a problem with some tooling (ask @argshook ) 

### 😯 Current Behavior

generated client project has husky and `lint-precommit` set up.

### 🤔 Expected Behaviour

Well, I don't expect the generator to have an option for `precommit` or `prepush`,
but I would like to know the Yoshi team's recommendation on how to do proper `prepush` linting.
### 💁 Possible Solution 

Use [`lint-prepush`](https://www.npmjs.com/package/lint-prepush) or something like it.
It does a `git diff` from current branch to `master branch (configurable), in order to know on which files to run (and not on ALL files in the project)

**Comment by ranyitz** [comment]
@hepiyellow Thanks for opening an issue.

I didn't understand the motivation, as you don't avoid the wait, you're moving it to the "push" part. Also, you've got to explain the "might be a problem" part.

This is an opinionated matter, so I'll try to explain why I think pre-commit is better than pre-push when talking about running the linter.

Let's say that you've done 4 commits and you're about to push your changes, the pre-push hook discovered some linting issues, formatting, unused variables etc... Those changes belong to different commits. Now you'll probably won't try to rebase each fix to each commit to make the history look sane for the reviewer, you'll patch the changes under a `"fix lint"` commit, which is acceptable but unquestionably less good of an option.

For me it makes more sense to check the linter before you seal a commit blob rather than before you sync with a remote repository.

**Comment by hepiyellow** [comment]
You are correct that in case of unused-vars, it is better to have each commit linted and fixed, so that the reviewer could review each commit separately.

> Just a note about that , usually, we squash & rebase PRs so the final outcome on master branch would be clean.

@argshook any comments here?

**Comment by ranyitz** [comment]
> usually, we squash & rebase PRs so the final outcome on master branch would be clean

@hepiyellow Not all projects do it, and we can argue whether it's a good thing or not. But you can always decide on which hook to use in your project.
