### ISSUE TITLE
`close of undefined` causes my tests to fail sometimes (flaky)

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/yoshi#922]
# 🐛 Bug Report

Flaky both on local machine and CI (can provide link to failed CI builds in Slack)

```
{ ShellJSInternalError: EEXIST: file already exists, mkdir '/Users/username/projects/projectname/target/logs'
    at Object.mkdirSync (fs.js:753:3)
    at mkdirSyncRecursive (/Users/username/projects/projectname/node_modules/shelljs/src/mkdir.js:24:8)
    at /Users/username/projects/projectname/node_modules/shelljs/src/mkdir.js:81:9
    at Array.forEach (<anonymous>)
    at Object._mkdir (/Users/username/projects/projectname/node_modules/shelljs/src/mkdir.js:59:8)
 FAIL   e2e  test/e2e/app.spec.tsis/projects/projectname/node_modules/shelljs/src/common.js:384:25)
  ● Test suite failed to run

    TypeError: Cannot read property 'close' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-yoshi-puppeteer/index.js:39:28)
          at Generator.throw (<anonymous>)

```
### 🌍 Your Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: Not Found
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    @storybook/core:  4.1.6 
    @storybook/react: ^4.1.4 => 4.1.6 
    babel-preset-yoshi:  3.17.0 
    eslint-config-yoshi:  3.25.1 
    eslint-config-yoshi-base:  3.25.1 
    jest-environment-yoshi-bootstrap:  3.23.0 
    jest-environment-yoshi-puppeteer:  3.24.1 
    jest-yoshi-preset: ^3.24.1 => 3.24.1 
    storybook: Not Found
    tslint-config-yoshi: ^3.22.5 => 3.22.5 
    tslint-config-yoshi-base:  3.22.5 
    typescript: ^3.2.2 => 3.2.2 
    webpack:  4.28.4 
    yoshi-config:  3.23.0 
    yoshi-helpers:  3.23.0 
    yoshi-runtime:  1.0.42 

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@sentry/browser": "Sentry"
  },
  "servers": {
    "cdn": {
      "ssl": false
    }
  },
  "hmr": "auto"
}
```

**Comment by sidoruk-sv** [comment]
Doesn't reproduced for now

**Comment by yaelz** [comment]
Happens to me too. Can we reopen this?

To anyone who encounters this again, here's a w/a:
https://github.com/wix-private/experts/blob/38c5dec5a04069d85320dca06abd10607d1db45f/experts-dashboard/test/environment.js#L88

Thanks to Ran Yitzhaki and Gal Schlezinger :)

**Comment by ranyitz** [comment]
Thanks @yaelz, opening

**Comment by ranyitz** [comment]
I'll elaborate

## The Problem 
Our server platform testkit creates a log directory for each instance, in case there is no custom `APP_LOG_DIR` environment variable supplied it's using the default one.

In some cases (when there are multiple workers in one jest run) we see failures due to creating the same log directory at the same time (race of conditions).

## Proposed solution
We need to provide a dynamic directory path based on the `worker-id`, so we'll verify that every log dir is tied with a specific jest worker.

I would use the same solution we have for `appConfDir` just with `appLogDir` and modify the templates to use that variable.

___________

We're also open for better ideas 😃 

PRs welcome 👍 

@yaelz @sidoruk-sv would one of you have the time to take this?

**Comment by yaelz** [comment]
Apparently it's not only the log dir, here's another failure, this time regarding target/persistent:
http://pullrequest-tc.dev.wixpress.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1587372&_focus=2160

So the solution should include all relevant folders.

@ranyitz I hope I can get to it in some guild day/week... But for now I don't see how I can do it

**Comment by ranyitz** [comment]
Thanks @yaelz That's correct.

These are the avialable environment paremeters defaults:

https://github.com/wix-platform/wix-node-platform/blob/41c81693b11bb1715ef900552a05cc3c9ce5dc7e/testing/env-support/index.js#L23-L24

To me it looks like `APP_CONF_DIR` `APP_LOG_DIR` & `APP_PERSISTENT_DIR` are the only directories that the `node_platfrom` write files into.

@hugebdu can you verify this assumption? (I think that `APP_TEMPL_DIR` is only for read purposes and therefore should remain 1)

**Comment by Enzewon** [comment]
Hi guys!

I've fixed this problem in `index-dev.js` using next:
```
....
(async () => {
  let appLogDir = './target/logs';
  if (fs.existsSync(appLogDir)) {
    appLogDir = null;
  }
  const app = bootstrapServer({
    port,
    managementPort: port + 1,
    appConfDir,
    appLogDir,
  });
...
```

Can we have any side effects with it?

**Comment by ranyitz** [comment]
This PR (https://github.com/wix/yoshi/pull/1132) has been merged into yoshi@4. It configures `APP_CONF_DIR`, `APP_LOG_DIR`, `APP_PERSISTENT_DIR` and any other environment parameters for the node platform, and put them on the `process.env` of the test environment and the start environment.

It means that in order to fix this kind of problem you need to do the following:

1. Verify that you are on Yoshi > 4
2. Do not pass any parameters to the config emitter and the bootstrap testkit
besides the environment itself: `env: process.env`

(hopefully, we won't need to pass that in the future)

You can look at the fullstack template for a proper way to configure the environment:

https://github.com/wix/yoshi/blob/201a065f334a647a8f533c6862f27b682554dfd1/packages/create-yoshi-app/templates/fullstack/javascript/environment.js#L8-L19

After doing so, you should not have any race of conditions.

Closing for now.
Please open if this problem is not solved with one of the solutions provided in this thread.
